name: Validate

on:
  push:
    branches:
      - test-361
#pull-request
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
      volumes: 
        - /home/runner/work/_actions/priyagupta108/srcomp-validate-action/test-action-361:/home/runner/work/_actions/priyagupta108/srcomp-validate-action/test-action-361
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - run: cat requirements.txt

      - name: Ensure Sudo is Installed
        run: |
          if ! command -v sudo &> /dev/null; then
            echo "sudo could not be found. Installing..."
            apt-get update && apt-get install -y sudo
          fi
      - name: Clear Python cache
        run: |
          sudo rm -rf /__t/Python
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io
      - name: Install lsb-release
        run: |
          apt-get update
          apt-get install -y lsb-release
      - name: Create /etc/lsb-release
        run: |
          echo "DISTRIB_RELEASE=24.04" | tee -a /etc/lsb-release
      - name: Change ownership of /github/home
        run: sudo chown -R $(whoami) /github/home
      - uses: priyagupta108/srcomp-validate-action@test-action-361
      - run: cat requirements.txt
