name: Validate

on:
  push:
    branches:
      - test-361
  pull_request:
  workflow_dispatch:
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - uses: priyagupta108/srcomp-validate-action@test-action-361
