name: Validate

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - run: cat requirements.txt
      - uses: priyagupta108/srcomp-validate-action@test-action-361
      - run: cat requirements.txt
